# Generated by Django 5.2.4 on 2025-07-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiquest',
            old_name='course_dueation',
            new_name='course_duration',
        ),
    ]
